// All mock feed data for Xene Milestone 1 visual shell
// Structured to match the FeedItem schema used by the real backend

export const MOCK_FEED = [
  // ── OBJEKT ──────────────────────────────────────────────────────────────────
  {
    id: 'obj-sc-001',
    platform: 'soundcloud',
    artist_name: 'Objekt',
    content_type: 'track',
    title: 'Agnes Apparatus (Warehouse Edit)',
    body: 'Unmastered rough from last month. Not for distribution.',
    artwork_url: 'https://picsum.photos/seed/objekt1/800/800',
    external_url: 'https://soundcloud.com/objekt/agnes-apparatus',
    published_at: '2026-04-10T22:14:00Z',
    play_count: 84200,
    like_count: 3100,
    waveform_url: 'https://wave.sndcdn.com/fake/objekt1',
  },
  {
    id: 'obj-sc-002',
    platform: 'soundcloud',
    artist_name: 'Objekt',
    content_type: 'track',
    title: 'Tinsel & Foil (Club Version)',
    body: null,
    artwork_url: 'https://picsum.photos/seed/objekt2/800/800',
    external_url: 'https://soundcloud.com/objekt/tinsel-foil',
    published_at: '2026-03-28T18:00:00Z',
    play_count: 122400,
    like_count: 5700,
    waveform_url: 'https://wave.sndcdn.com/fake/objekt2',
  },
  {
    id: 'obj-sc-003',
    platform: 'soundcloud',
    artist_name: 'Objekt',
    content_type: 'track',
    title: 'Needle & Thread',
    body: 'From the Flatland LP sessions. Unreleased.',
    artwork_url: 'https://picsum.photos/seed/objekt3/800/800',
    external_url: 'https://soundcloud.com/objekt/needle-thread',
    published_at: '2026-03-15T12:30:00Z',
    play_count: 61800,
    like_count: 2900,
    waveform_url: 'https://wave.sndcdn.com/fake/objekt3',
  },
  {
    id: 'obj-ig-001',
    platform: 'instagram',
    artist_name: 'Objekt',
    content_type: 'post',
    title: null,
    body: 'Berlin → Amsterdam → London. Three dates, two weeks. See you in the dark.',
    artwork_url: 'https://picsum.photos/seed/objekt-ig1/600/600',
    external_url: 'https://instagram.com/p/fake001',
    published_at: '2026-04-08T14:22:00Z',
    play_count: null,
    like_count: 4800,
    waveform_url: null,
  },
  {
    id: 'obj-ig-002',
    platform: 'instagram',
    artist_name: 'Objekt',
    content_type: 'image',
    title: null,
    body: 'Flatland vinyl repress. 300 copies. Friday.',
    artwork_url: 'https://picsum.photos/seed/objekt-ig2/600/600',
    external_url: 'https://instagram.com/p/fake002',
    published_at: '2026-04-01T10:00:00Z',
    play_count: null,
    like_count: 7200,
    waveform_url: null,
  },
  {
    id: 'obj-bc-001',
    platform: 'bandcamp',
    artist_name: 'Objekt',
    content_type: 'release',
    title: 'Flatland LP — Repress',
    body: '2026 repress of the 2014 debut. Remastered for the original plates. Limited to 300.',
    artwork_url: 'https://picsum.photos/seed/objekt-bc1/800/800',
    external_url: 'https://objekt.bandcamp.com/album/flatland-repress',
    published_at: '2026-04-05T12:00:00Z',
    play_count: null,
    like_count: null,
    waveform_url: null,
  },

  // ── SHACKLETON ───────────────────────────────────────────────────────────────
  {
    id: 'shk-bc-001',
    platform: 'bandcamp',
    artist_name: 'Shackleton',
    content_type: 'release',
    title: 'Departing Like Rivers',
    body: 'New full-length. 12 movements. Available on limited white-label vinyl and digital.',
    artwork_url: 'https://picsum.photos/seed/shackleton1/800/800',
    external_url: 'https://shackleton.bandcamp.com/album/departing-like-rivers',
    published_at: '2026-04-12T08:00:00Z',
    play_count: null,
    like_count: null,
    waveform_url: null,
  },
  {
    id: 'shk-bc-002',
    platform: 'bandcamp',
    artist_name: 'Shackleton',
    content_type: 'release',
    title: 'The Rope Uncoils — EP',
    body: 'Four tracks for a specific room at a specific hour. Recorded live at Cafe OTO.',
    artwork_url: 'https://picsum.photos/seed/shackleton2/800/800',
    external_url: 'https://shackleton.bandcamp.com/album/the-rope-uncoils',
    published_at: '2026-02-20T10:00:00Z',
    play_count: null,
    like_count: null,
    waveform_url: null,
  },
  {
    id: 'shk-sc-001',
    platform: 'soundcloud',
    artist_name: 'Shackleton',
    content_type: 'track',
    title: 'Blood on My Hands (Extended Ritual Mix)',
    body: null,
    artwork_url: 'https://picsum.photos/seed/shackleton3/800/800',
    external_url: 'https://soundcloud.com/shackleton/blood-ritual',
    published_at: '2026-03-03T19:00:00Z',
    play_count: 38900,
    like_count: 1600,
    waveform_url: 'https://wave.sndcdn.com/fake/shackleton1',
  },

  // ── CALL SUPER ───────────────────────────────────────────────────────────────
  {
    id: 'cs-ig-001',
    platform: 'instagram',
    artist_name: 'Call Super',
    content_type: 'post',
    title: null,
    body: "New record done. It took a long time and now it's done and it sounds like this.",
    artwork_url: 'https://picsum.photos/seed/callsuper1/600/600',
    external_url: 'https://instagram.com/p/fake003',
    published_at: '2026-04-11T16:45:00Z',
    play_count: null,
    like_count: 5100,
    waveform_url: null,
  },
  {
    id: 'cs-ig-002',
    platform: 'instagram',
    artist_name: 'Call Super',
    content_type: 'image',
    title: null,
    body: 'Fabric Promo. May 3rd.',
    artwork_url: 'https://picsum.photos/seed/callsuper2/600/600',
    external_url: 'https://instagram.com/p/fake004',
    published_at: '2026-04-03T11:30:00Z',
    play_count: null,
    like_count: 2900,
    waveform_url: null,
  },
  {
    id: 'cs-ig-003',
    platform: 'instagram',
    artist_name: 'Call Super',
    content_type: 'image',
    title: null,
    body: null,
    artwork_url: 'https://picsum.photos/seed/callsuper3/600/600',
    external_url: 'https://instagram.com/p/fake005',
    published_at: '2026-03-22T09:00:00Z',
    play_count: null,
    like_count: 3700,
    waveform_url: null,
  },
  {
    id: 'cs-sc-001',
    platform: 'soundcloud',
    artist_name: 'Call Super',
    content_type: 'track',
    title: 'Alrite',
    body: 'From the new LP. Out on Hessle Audio.',
    artwork_url: 'https://picsum.photos/seed/callsuper4/800/800',
    external_url: 'https://soundcloud.com/callsuper/alrite',
    published_at: '2026-04-09T13:00:00Z',
    play_count: 29400,
    like_count: 1800,
    waveform_url: 'https://wave.sndcdn.com/fake/callsuper1',
  },
  {
    id: 'cs-sc-002',
    platform: 'soundcloud',
    artist_name: 'Call Super',
    content_type: 'track',
    title: 'WDDM',
    body: null,
    artwork_url: 'https://picsum.photos/seed/callsuper5/800/800',
    external_url: 'https://soundcloud.com/callsuper/wddm',
    published_at: '2026-03-18T20:00:00Z',
    play_count: 44700,
    like_count: 2200,
    waveform_url: 'https://wave.sndcdn.com/fake/callsuper2',
  },
  {
    id: 'cs-bp-001',
    platform: 'beatport',
    artist_name: 'Call Super',
    content_type: 'release',
    title: 'WDDM EP',
    body: 'Four tracks. Techno / Deep Techno. Hessle Audio. Out now.',
    artwork_url: 'https://picsum.photos/seed/callsuper6/800/800',
    external_url: 'https://www.beatport.com/release/wddm-ep/fake001',
    published_at: '2026-04-07T00:00:00Z',
    play_count: null,
    like_count: null,
    waveform_url: null,
  },
]

export const MOCK_ARTISTS = [
  { id: 'objekt',    name: 'Objekt',     platforms: ['soundcloud', 'instagram', 'bandcamp'] },
  { id: 'shackleton',name: 'Shackleton', platforms: ['bandcamp', 'soundcloud'] },
  { id: 'callsuper', name: 'Call Super', platforms: ['instagram', 'soundcloud', 'beatport'] },
]
